name 'ownberry'
maintainer 'wschiffels'
maintainer_email 'me@me'
license 'WTFPL'
description 'this is for testing only, though it should basically work'
version '0.0.1'
recipe 'ownberry::default', 'play around with chef'
supports 'debian', '= 7.8'

depends 'mysqld'
depends 'nginx'
depends 'openssl'
depends 'php-fpm'
depends 'archive'
