name 'ownberry'
maintainer 'me'
maintainer_email 'me@me'
license 'WTFPL'
description 'unusable test thing'
version '0.0.1'
recipe 'ownberry::default', 'highly unusable test thing'

depends 'mysqld'
depends 'nginx'
depends 'openssl'
depends 'php-fpm'
depends 'archive'
