name 'chef_pi'
maintainer 'me'
maintainer_email 'me@me'
license 'WTFPL'
description 'unusable test thing'
version '0.0.1'
recipe 'chef_pi::default', 'highly unusable test thing'

depends 'mysqld'
depends 'nginx'
depends 'openssl'
depends 'php-fpm'
